/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "userdefs-base.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccDummyBase_T_Initialize(asn1SccDummyBase_T* pVal)
{
    *pVal = (asn1SccDummyBase_T) 0;
}
#endif

 
flag asn1SccDummyBase_T_IsConstraintValid(const asn1SccDummyBase_T* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccT_UInt32_IsConstraintValid(pVal, pErrCode);

	return ret;
}

flag asn1SccDummyBase_T_Encode(const asn1SccDummyBase_T* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccDummyBase_T_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    ret = asn1SccT_UInt32_Encode(pVal, pBitStrm, pErrCode, FALSE);
    }

	return ret;
}

flag asn1SccDummyBase_T_Decode(asn1SccDummyBase_T* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = asn1SccT_UInt32_Decode(pVal, pBitStrm, pErrCode);

	return ret;
}

const asn1SccT_UInt32 numBase_JointTrajectory = 200;

const asn1SccT_UInt32 numStd_orogen_typekits_mtype_std_vector_base_JointTransform = 200;

const asn1SccT_UInt32 numStd_orogen_typekits_mtype_std_vector_base_Waypoint = 200;

const asn1SccT_UInt32 numStd_orogen_typekits_mtype_std_vector_base_Wrench = 200;

const asn1SccT_UInt32 numStd_vector_Wrappers_Vector4d = 200;

const asn1SccT_UInt32 numStd_orogen_typekits_mtype_std_vector_base_Trajectory = 200;

const asn1SccT_UInt32 numBase_JointLimits_names = 200;

const asn1SccT_UInt32 numBase_JointLimits_elements = 200;

const asn1SccT_UInt32 numBase_JointsTrajectory_names = 200;

const asn1SccT_UInt32 numBase_JointsTrajectory_elements = 200;

const asn1SccT_UInt32 numBase_JointsTrajectory_times_val = 200;

const asn1SccT_UInt32 numBase_NamedVector_Base_JointLimitRange_names = 200;

const asn1SccT_UInt32 numBase_NamedVector_Base_JointLimitRange_elements = 200;

const asn1SccT_UInt32 numBase_NamedVector_Base_JointState_names = 200;

const asn1SccT_UInt32 numBase_NamedVector_Base_Wrench_names = 200;

const asn1SccT_UInt32 numBase_NamedVector_Base_Wrench_elements = 200;

const asn1SccT_UInt32 numBase_NamedVector_Base_JointTrajectory_names = 200;

const asn1SccT_UInt32 numBase_NamedVector_Base_JointTrajectory_elements = 200;

const asn1SccT_UInt32 numBase_samples_DepthMap_timestamps = 200;

const asn1SccT_UInt32 numBase_samples_DepthMap_vertical_interval = 200;

const asn1SccT_UInt32 numBase_samples_DepthMap_horizontal_interval = 200;

const asn1SccT_UInt32 numBase_samples_DepthMap_distances = 200;

const asn1SccT_UInt32 numBase_samples_DepthMap_remissions = 200;

const asn1SccT_UInt32 numBase_samples_DistanceImage_data = 200;

const asn1SccT_UInt32 numBase_commands_Joints_names = 200;

const asn1SccT_UInt32 numBase_samples_LaserScan_ranges = 200;

const asn1SccT_UInt32 numBase_samples_LaserScan_remission = 200;

const asn1SccT_UInt32 numBase_samples_Pointcloud_points = 200;

const asn1SccT_UInt32 numBase_samples_Pointcloud_colors = 200;

const asn1SccT_UInt32 numBase_samples_Sonar_timestamps = 200;

const asn1SccT_UInt32 numBase_samples_Sonar_bearings = 200;

const asn1SccT_UInt32 numBase_samples_Sonar_bins = 200;

const asn1SccT_UInt32 numBase_samples_SonarBeam_beam = 200;

const asn1SccT_UInt32 numBase_samples_SonarScan_data = 200;

const asn1SccT_UInt32 numBase_samples_SonarScan_time_beams = 200;

const asn1SccT_UInt32 numBase_samples_Wrenches_names = 200;

const asn1SccT_UInt32 numBase_samples_Wrenches_elements = 200;

const asn1SccT_UInt32 numBase_JointTransformVector_names = 200;

const asn1SccT_UInt32 numBase_JointTransformVector_elements = 200;

const asn1SccT_UInt32 numBase_NamedVector_Base_JointTransform_names = 200;

const asn1SccT_UInt32 numBase_NamedVector_Base_JointTransform_elements = 200;

const asn1SccT_UInt32 numBase_samples_frame_Frame_image = 200;

const asn1SccT_UInt32 numBase_samples_frame_Frame_attributes = 200;

const asn1SccT_UInt32 numWrappers_MatrixXd_data = 200;

const asn1SccT_UInt32 numWrappers_VectorXd_data = 200;

const asn1SccT_UInt32 numBase_JointTransformVector_m_names = 200;

const asn1SccT_UInt32 numBase_NamedVector_base_JointTransform_m_names = 200;

const asn1SccT_UInt32 numBase_NamedVector_base_Wrench_m_names = 200;

const asn1SccT_UInt32 numBase_samples_Pointcloud_m_points = 200;

const asn1SccT_UInt32 numBase_samples_Pointcloud_m_colors = 200;

const asn1SccT_UInt32 numBase_samples_Wrenches_m_names = 200;

const asn1SccT_UInt32 numWrappers_geometry_Spline_knots = 200;

const asn1SccT_UInt32 numWrappers_geometry_Spline_vertices = 200;
